import { type Formula, type Ingredient, type Note, type OlfactiveFamily } from "@/lib/types";

const ingredients: Ingredient[] = [
  {
    id: "1",
    name: "Bergamot",
    concentration: 15.0,
    vendor: "Perfumer's Apprentice",
    dilution: 100,
    cost: 0.12,
    note: "Top",
    olfactiveFamilies: ["Citrus", "Fruity"],
    isAllergen: true,
    ifraLimit: 20.0,
  },
  {
    id: "2",
    name: "Jasmine Absolute",
    concentration: 2.5,
    vendor: "Givaudan",
    dilution: 10,
    cost: 15.5,
    note: "Mid",
    olfactiveFamilies: ["Floral", "Animalic"],
    isAllergen: true,
    ifraLimit: 0.7,
  },
  {
    id: "3",
    name: "Rose Otto",
    concentration: 11.0,
    vendor: "Firmenich",
    dilution: 100,
    cost: 12.0,
    note: "Mid",
    olfactiveFamilies: ["Floral", "Spicy"],
    isAllergen: true,
    ifraLimit: 1.25,
  },
  {
    id: "4",
    name: "Sandalwood",
    concentration: 8.0,
    vendor: "Perfumer's World",
    dilution: 100,
    cost: 2.5,
    note: "Base",
    olfactiveFamilies: ["Woody"],
    isAllergen: false,
    ifraLimit: 15.0,
  },
  {
    id: "5",
    name: "Vetiver",
    concentration: 6.0,
    vendor: "Symrise",
    dilution: 100,
    cost: 0.8,
    note: "Base",
    olfactiveFamilies: ["Woody", "Earthy"],
    isAllergen: false,
    ifraLimit: 15.0,
  },
    {
    id: "6",
    name: "Iso E Super",
    concentration: 22.5,
    vendor: "IFF",
    dilution: 100,
    cost: 0.05,
    note: "Base",
    olfactiveFamilies: ["Woody", "Amber"],
    isAllergen: false,
    ifraLimit: 25.0,
  },
  {
    id: "7",
    name: "Ethanol",
    concentration: 35.0,
    vendor: "Lab Solvent",
    dilution: 100,
    cost: 0.01,
    note: "Top",
    olfactiveFamilies: [],
    isAllergen: false,
    ifraLimit: 100,
  },
];

export const initialFormula: Formula = {
  id: "f-01",
  name: "Ethereal Bloom",
  ingredients: ingredients,
};

export const olfactiveFamilies: OlfactiveFamily[] = [
  "Floral",
  "Woody",
  "Citrus",
  "Fruity",
  "Spicy",
  "Green",
  "Gourmand",
  "Aquatic",
  "Amber",
  "Musky",
  "Animalic",
  "Earthy",
];

export const notes: Note[] = ["Top", "Mid", "Base"];
