import { Ingredient } from './types';

export const importedMaterials: Ingredient[] = [
  {
    "id": "unknown",
    "name": "Unknown Material",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=284840886",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 100,
    "description": "Some proprietary mixtures don't list all of their materials (ie. Heliotropex N). In these cases, this material represents the unknown components with no IFRA restrictions.",
    "longevity": 4,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "perfumers_alcohol",
    "name": "Perfumer's Alcohol",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=182588244",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 100,
    "description": "Perfumer's Alcohol (SDA 40B, 190 proof). Commonly used as a fixative for perfume materials.",
    "longevity": 4,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "propylene_glycol",
    "name": "Propylene Glycol",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=653536315",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 100,
    "casNumber": "57-55-6",
    "description": "Used as a solvent in some cases.",
    "longevity": 4,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "dpg",
    "name": "Dipropylene Glycol",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=99675",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 100,
    "description": "Dipropylene Glycol (DPG) is practically odorless and used typically for diluting perfume materials.",
    "longevity": 4,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "ipm",
    "name": "Isopropyl Myristate",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=104486",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 100,
    "description": "Isopropyl Myristate is practically odorless and used typically for diluting perfume materials.",
    "longevity": 4,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "tec",
    "name": "Triethyl Citrate",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=114706",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 100,
    "casNumber": "77-93-0",
    "description": "A versatile solvent for oily products, crystals, powders and resins.",
    "longevity": 4,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "benzyl_benzoate",
    "name": "Benzyl Benzoate",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=2087255921",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 100,
    "casNumber": "120-51-4",
    "description": "A useful solvent for nitro-musks, certain EOs and other very low-polarity ingredients that can be difficult to dissolve.",
    "longevity": 4,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "triplal",
    "name": "Triplal",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=1059618990",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Green"
    ],
    "isAllergen": true,
    "ifraLimit": 2.5,
    "casNumber": "68039-49-6",
    "description": "Great for creating a green accord. It blends beautifully with fruity, citrus, and floral compositions.",
    "longevity": 4,
    "impact": 800,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "ethyl_safranate",
    "name": "Ethyl Safranate",
    "imageUrl": "https://loremflickr.com/320/240/spice?lock=1629696552",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Rose",
      "Fruity",
      "Apple",
      "Spicy"
    ],
    "isAllergen": false,
    "ifraLimit": 22,
    "casNumber": "35044-59-8",
    "description": "A complex, diffusive, spicy rose note with apple cider and spicy aspects. Used in floral and fruity compositions.",
    "longevity": 0.2,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "safranal",
    "name": "Safranal",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1776690098",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Tobacco",
      "Saffron",
      "Herbal"
    ],
    "isAllergen": true,
    "ifraLimit": 0.012,
    "casNumber": "116-26-7",
    "description": "Powerful saffron builder.",
    "longevity": 24,
    "impact": 400,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "safraleine",
    "name": "Safraleine",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1999526880",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Saffron",
      "Leather",
      "Herbal",
      "Tobacco"
    ],
    "isAllergen": false,
    "ifraLimit": 3,
    "casNumber": "54440-17-4",
    "description": "Exhibits leather and tobacco facets but also has characteristics of spices reminiscent of natural saffron, enriched by rose ketone-like floral aspects.",
    "longevity": 168,
    "impact": 400,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "ionone_alpha",
    "name": "Ionone Alpha",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=561893181",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Orris",
      "Violet"
    ],
    "isAllergen": false,
    "ifraLimit": 6,
    "casNumber": "127-41-3",
    "description": "Orris and violet builder.",
    "longevity": 100,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "citronellol",
    "name": "Citronellol",
    "imageUrl": "https://loremflickr.com/320/240/citrus?lock=383544097",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Fresh",
      "Rose",
      "Citrus",
      "Pine",
      "Geranium"
    ],
    "isAllergen": true,
    "ifraLimit": 12,
    "casNumber": "106-22-9",
    "description": "Rose, muguet, geranium builder.",
    "longevity": 20,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "dynascone",
    "name": "Dynascone",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=1797282318",
    "vendor": "Firmenich",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Green",
      "Galbanum",
      "Fruity",
      "Pineapple",
      "Hyacinth"
    ],
    "isAllergen": true,
    "ifraLimit": 1.0999999999999999,
    "casNumber": "56973-85-4",
    "description": "An extremely powerful and diffusive material useful for fruity, green and floral compositions.",
    "longevity": 340,
    "impact": 200,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "geraniol",
    "name": "Geraniol",
    "imageUrl": "https://loremflickr.com/320/240/citrus?lock=1921082853",
    "vendor": "Firmenich",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Rose",
      "Geranium",
      "Fruity",
      "Citrus",
      "Waxy"
    ],
    "isAllergen": true,
    "ifraLimit": 4.7,
    "casNumber": "106-24-1",
    "description": "Used generally as a sweet floral material of outstanding versatility.",
    "longevity": 18,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "zenolide",
    "name": "Zenolide",
    "imageUrl": "https://loremflickr.com/320/240/cloud?lock=573093610",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Musk",
      "Berry"
    ],
    "isAllergen": false,
    "ifraLimit": 40,
    "casNumber": "54982-83-1",
    "description": "Great for creating a clean, soft white musk note. Not extremely noticeable.",
    "longevity": 320,
    "impact": 80,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "cinnamic_alcohol",
    "name": "Cinnamic Alcohol",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=838498885",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Balsamic",
      "Cinnamon",
      "Powdery"
    ],
    "isAllergen": true,
    "ifraLimit": 1.2,
    "casNumber": "104-54-1",
    "description": "Cinnamon builder. Also known as Cinnamyl Alcohol.",
    "longevity": 60,
    "impact": 80,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "methyl_isoeugenol",
    "name": "Methyl Isoeugenol",
    "imageUrl": "https://loremflickr.com/320/240/spice?lock=1879348104",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Spicy",
      "Clove"
    ],
    "isAllergen": true,
    "ifraLimit": 0.016,
    "casNumber": "93-16-3",
    "description": "Spicy note useful for clove and spice accords and some floral accords. Also known as Methyl Eugenol.",
    "longevity": 24,
    "impact": 160,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "heliotropin",
    "name": "Heliotropin",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1034095879",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Heliotrope",
      "Powdery",
      "Cherry",
      "Balsamic"
    ],
    "isAllergen": false,
    "ifraLimit": 100,
    "casNumber": "120-57-0",
    "description": "Heliotrope, cherry and vanilla builder. Also known as Piperonal. IFRA restriction unknown at this time.",
    "longevity": 24,
    "impact": 160,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "anisaldehyde",
    "name": "Anisaldehyde",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=256489557",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Anise",
      "Lilac",
      "Hawthorn",
      "Heliotrope"
    ],
    "isAllergen": true,
    "ifraLimit": 0.21,
    "casNumber": "123-11-5",
    "description": "The main component for numerous floral accords like lilac, hawthorn, anise, honeysuckle, heliotrope, etc.",
    "longevity": 28,
    "impact": 130,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "veratric_aldehyde",
    "name": "Veratric Aldehyde",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=864250151",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Vanilla",
      "Wood",
      "Heliotrope",
      "Coumarin"
    ],
    "isAllergen": false,
    "ifraLimit": 15,
    "casNumber": "120-14-9",
    "description": "More warmth and depth than Vanillin, and excellent effect in spicy and woody-musky accords.",
    "longevity": 28,
    "impact": 130,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "acetate_c6",
    "name": "Acetate C6",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=2037617519",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Green",
      "Fruity",
      "Pear",
      "Apple"
    ],
    "isAllergen": true,
    "ifraLimit": 10,
    "casNumber": "142-92-7",
    "description": "Good blender and modifier for Labdanum. Good for sweet fruity accords. Also known as Hexyl Acetate.",
    "longevity": 0.2,
    "impact": 220,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "acetate_c9",
    "name": "Acetate C9",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=2037617516",
    "vendor": "Vigon",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Tropical",
      "Fruity",
      "Waxy"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "143-13-5",
    "description": "Adds freshness and diffusion. Also known as Nonyl Acetate.",
    "longevity": 12,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "acetate_c12",
    "name": "Acetate C12",
    "imageUrl": "https://loremflickr.com/320/240/citrus?lock=1258366246",
    "vendor": "Vigon",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Citrus",
      "Fresh",
      "Fruity",
      "Waxy"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "112-66-3",
    "description": "Also known as Lauryl Acetate or Dodecyl Acetate.",
    "longevity": 238,
    "impact": 100,
    "concentration": 20,
    "dilution": 20
  },
  {
    "id": "damascone_alpha",
    "name": "Damascone Alpha",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=186368380",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Apple",
      "Plum",
      "Green",
      "Rose"
    ],
    "isAllergen": true,
    "ifraLimit": 0.02,
    "casNumber": "24720-09-0",
    "description": "Rose, fruit and plum booster.",
    "longevity": 150,
    "impact": 700,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "damascone_beta",
    "name": "Damascone Beta",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=698725366",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Rose",
      "Tobacco",
      "Honey",
      "Plum",
      "Cassis"
    ],
    "isAllergen": true,
    "ifraLimit": 0.02,
    "casNumber": "23726-91-2",
    "description": "A very powerful fruity floral booster.",
    "longevity": 180,
    "impact": 450,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "damascone_delta",
    "name": "Damascone Delta",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=183809826",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Cassis",
      "Tobacco",
      "Apple",
      "Plum",
      "Rose"
    ],
    "isAllergen": true,
    "ifraLimit": 0.02,
    "casNumber": "57378-68-4",
    "description": "Very diffusive plum and rose builder.",
    "longevity": 220,
    "impact": 450,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "damascone_gamma",
    "name": "Damascone Gamma",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=181157683",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Rose",
      "Apple",
      "Plum",
      "Green",
      "Tobacco"
    ],
    "isAllergen": true,
    "ifraLimit": 0.02,
    "casNumber": "35087-49-1",
    "description": "Very diffusive plum and rose builder.",
    "longevity": 48,
    "impact": 450,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "terpinene_alpha",
    "name": "Terpinene Alpha",
    "imageUrl": "https://loremflickr.com/320/240/pine?lock=429286631",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Terpy",
      "Pine",
      "Citrus",
      "Spicy"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "99-86-5",
    "description": "Citrus builder, pine builder, spice builder.",
    "longevity": 3,
    "impact": 50,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "ethyl_propionate",
    "name": "Ethyl Propionate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=2092657056",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Fruity",
      "Grape",
      "Rum",
      "Pineapple"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "105-37-3",
    "description": "Pineapple builder, rum builder.",
    "longevity": 4,
    "impact": 200,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "allyl_caproate",
    "name": "Allyl Caproate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=458929650",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Pineapple",
      "Rum",
      "Fruity",
      "Wine"
    ],
    "isAllergen": false,
    "ifraLimit": 20,
    "casNumber": "123-68-2",
    "description": "Pineapple builder, rum builder, wine builder.",
    "longevity": 2,
    "impact": 250,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "hexalon",
    "name": "Hexalon",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=816466149",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Fruity",
      "Pineapple",
      "Orris"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "79-78-7",
    "description": "Pineapple builder.",
    "longevity": 80,
    "impact": 140,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "delphol_hc",
    "name": "Delphol HC",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=1691381446",
    "vendor": "Firmenich",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Green",
      "Jasmine",
      "Magnolia",
      "Tea",
      "Fruity"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "84560-00-9",
    "description": "Tea builder, white floral builder, fruit builder.",
    "longevity": 48,
    "impact": 80,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "citral_dimethyl_acetal",
    "name": "Citral Dimethyl Acetal",
    "imageUrl": "https://loremflickr.com/320/240/citrus?lock=833525319",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Citrus",
      "Verbena",
      "Lemon"
    ],
    "isAllergen": false,
    "ifraLimit": 15,
    "casNumber": "7549-37-3",
    "description": "Lemon, verbena and citrus builder.",
    "longevity": 7,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "methyl_cinnamic_aldehyde",
    "name": "Methyl Cinnamic Aldehyde",
    "imageUrl": "https://loremflickr.com/320/240/spice?lock=900901359",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Cinnamon",
      "Spicy"
    ],
    "isAllergen": true,
    "ifraLimit": 1.5,
    "casNumber": "101-39-3",
    "description": "Also called Cyprinal or Cinnamaldehyde. Cinnamon builder.",
    "longevity": 240,
    "impact": 50,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "cinnamyl_acetate",
    "name": "Cinnamyl Acetate",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=969358407",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Cinnamon",
      "Balsamic",
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "103-54-8",
    "description": "Cinnamon builder. Very strong at 5% of concentration.",
    "longevity": 46,
    "impact": 120,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "benzyl_cinnamate",
    "name": "Benzyl Cinnamate",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=232256163",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Balsamic",
      "Cinnamon"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "103-41-3",
    "description": "Cinnamon builder.",
    "longevity": 243,
    "impact": 25,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "eugenol",
    "name": "Eugenol",
    "imageUrl": "https://loremflickr.com/320/240/spice?lock=1403557251",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Clove",
      "Spicy"
    ],
    "isAllergen": true,
    "ifraLimit": 2.5,
    "casNumber": "97-53-0",
    "description": "Clove builder.",
    "longevity": 48,
    "impact": 175,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "benzoic_acid",
    "name": "Benzoic Acid",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1143984190",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Benzoin",
      "Balsamic"
    ],
    "isAllergen": false,
    "ifraLimit": 0.6,
    "casNumber": "65-85-0",
    "description": "Benzoin builder. ",
    "longevity": 4,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "ethanol",
    "name": "Ethanol",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1431382045",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [],
    "isAllergen": false,
    "ifraLimit": 100,
    "casNumber": "64-17-5",
    "description": "Booze builder.",
    "longevity": 4,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "ethyl_vanillin",
    "name": "Ethyl Vanillin",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1933224382",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Caramel",
      "Vanilla"
    ],
    "isAllergen": false,
    "ifraLimit": 4,
    "casNumber": "121-32-4",
    "description": "Vanilla builder.",
    "longevity": 270,
    "impact": 600,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "vanillin",
    "name": "Vanillin",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1363765941",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Vanilla"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "121-33-5",
    "description": "Vanilla builder. Sweet, creamy, powdery, and balsamic.",
    "longevity": 400,
    "impact": 60,
    "flashPoint": 153,
    "vaporPressure": 0.0001,
    "smiles": "COC1=C(C=CC(=C1)C=O)O",
    "olfactoryProfile": { "Sweet": 95, "Creamy": 80, "Powdery": 60 },
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "ethyl_heptoate",
    "name": "Ethyl Heptoate",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1668740233",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Rum",
      "Wine",
      "Pineapple",
      "Brandy",
      "Berry"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "106-30-9",
    "description": "Also called Oenanthic Ether. Booze builder. Fruit builder. Diffusive and strong, but not long lasting.",
    "longevity": 2,
    "impact": 150,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "butyl_propionate",
    "name": "Butyl Propionate",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=825238920",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Banana",
      "Cherry",
      "Rum"
    ],
    "isAllergen": false,
    "ifraLimit": 4,
    "casNumber": "590-01-2",
    "description": "Booze builder. Cherry builder. Banana builder.",
    "longevity": 2,
    "impact": 150,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "cedryl_acetate",
    "name": "Cedryl Acetate",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=197747685",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Vetiver",
      "Cedar"
    ],
    "isAllergen": false,
    "ifraLimit": 13,
    "casNumber": "77-54-3",
    "description": "Long lasting cedar builder. ",
    "longevity": 40,
    "impact": 60,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "vertenex",
    "name": "Vertenex",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1984249907",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Orris",
      "Wood",
      "Balsamic"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "32210-23-4",
    "description": "Long lasting cedar builder.",
    "longevity": 22,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "ambercore",
    "name": "Ambercore",
    "imageUrl": "https://loremflickr.com/320/240/amber?lock=1539274498",
    "vendor": "Kao",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Amber"
    ],
    "isAllergen": false,
    "ifraLimit": 40,
    "casNumber": "139504-68-0",
    "description": "Amber builder. Blends well with floral and citrus.",
    "longevity": 168,
    "impact": 200,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "poivrol",
    "name": "Poivrol",
    "imageUrl": "https://loremflickr.com/320/240/spice?lock=400368925",
    "vendor": "Symrise",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Pepper",
      "Spicy"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "68966-86-9",
    "description": "Very diffusive. Imparts fresh spicy top note accents, and helps implement the spicy character in agarwood.",
    "longevity": 10,
    "impact": 50,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "isobutyl_quinoline",
    "name": "Isobutyl Quinoline",
    "imageUrl": "https://loremflickr.com/320/240/soil?lock=647838742",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Vetiver",
      "Tobacco",
      "Leather",
      "Earthy",
      "Oakmoss"
    ],
    "isAllergen": true,
    "ifraLimit": 10,
    "casNumber": "1333-58-0",
    "description": "Resembles certain facets of oakmoss and vetivert and blends very well with them.",
    "longevity": 50,
    "impact": 450,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "kohinool",
    "name": "Kohinool",
    "imageUrl": "https://loremflickr.com/320/240/amber?lock=308594243",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Amber",
      "Tobacco",
      "Raisin"
    ],
    "isAllergen": false,
    "ifraLimit": 35,
    "casNumber": "87118-95-4",
    "description": "Amber builder. Also called Amber Carbinol.",
    "longevity": 44,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "datilat",
    "name": "Datilat",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1443445933",
    "vendor": "Symrise",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Date",
      "Fig",
      "Raisin",
      "Brandy"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "68039-69-0",
    "description": "Adds a natural fruity twist to floral notes. Raisin, prune, date, and fig builder. Brandy builder.",
    "longevity": 41,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "symroxane",
    "name": "Symroxane",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=51379108",
    "vendor": "Symrise",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Tobacco",
      "Vetiver"
    ],
    "isAllergen": false,
    "ifraLimit": 3,
    "casNumber": "393517-29-8",
    "description": "Harmonizes woody and floral elements. Increases radiance and elegance. Imparts damascenone-like effects.",
    "longevity": 192,
    "impact": 50,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "methyl_anthranilate",
    "name": "Methyl Anthranilate",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=1964297809",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Fruity",
      "Floral",
      "Grape",
      "Orangeblossom"
    ],
    "isAllergen": true,
    "ifraLimit": 10,
    "casNumber": "134-20-3",
    "description": "Used in many types of floral blends such as neroli, orange blossom, exotic compositions, gardenia, tuberose and jasmine.",
    "longevity": 48,
    "impact": 420,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "methyl_diantilis",
    "name": "Methyl Diantilis",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=716587439",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Carnation",
      "Vanilla",
      "Powdery"
    ],
    "isAllergen": false,
    "ifraLimit": 3,
    "casNumber": "5595-79-9",
    "description": "An elegant, spicy, sweet ingredient with a similar profile to Isoeugenol, but with an additional powdery aspect.",
    "longevity": 400,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "ethyl_caprate",
    "name": "Ethyl Caprate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=1003707169",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Apple",
      "Grape",
      "Brandy",
      "Fruity",
      "Waxy"
    ],
    "isAllergen": false,
    "ifraLimit": 4,
    "casNumber": "110-38-3",
    "description": "Booze builder. Grape builder. Apple builder. Also called Ethyl Decanoate.",
    "longevity": 44,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "benzaldehyde",
    "name": "Benzaldehyde",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1371581555",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Cherry",
      "Almond",
      "Heliotrope",
      "Violet"
    ],
    "isAllergen": true,
    "ifraLimit": 0.25,
    "casNumber": "100-52-7",
    "description": "Cherry builder. Almond builder. Useful with heliotrope and violet accords.",
    "longevity": 1.5,
    "impact": 500,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "coumarin",
    "name": "Coumarin",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=373498086",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Tonka",
      "Coumarin",
      "Tobacco",
      "Hay"
    ],
    "isAllergen": true,
    "ifraLimit": 1.5,
    "casNumber": "91-64-5",
    "description": "Hay note, tobacco builder, tonka builder.",
    "longevity": 85,
    "impact": 120,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "isoeugenol",
    "name": "Isoeugenol",
    "imageUrl": "https://loremflickr.com/320/240/spice?lock=2083052968",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Clove",
      "Spicy",
      "Carnation",
      "Rose"
    ],
    "isAllergen": true,
    "ifraLimit": 0.11,
    "casNumber": "97-54-1",
    "description": "Carnation builder, Rose builder, used in oriental and fougere compositions.",
    "longevity": 60,
    "impact": 85,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "tobacarol",
    "name": "Tobacarol",
    "imageUrl": "https://loremflickr.com/320/240/amber?lock=619605239",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Tobacco",
      "Amber",
      "Wood"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "1209-61-6",
    "description": "Tobacco builder, amber builder.",
    "longevity": 52,
    "impact": 80,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "azarbre",
    "name": "Azarbre",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=520624213",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Orris",
      "Wood",
      "Honey",
      "Iris"
    ],
    "isAllergen": true,
    "ifraLimit": 10,
    "casNumber": "68845-36-3",
    "description": "Enhances ionones at 2-3% of concentrate. When used at higher dosages up to 10%, it blends the woody and floral components of a fragrance together.",
    "longevity": 24,
    "impact": 120,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "isobutavan",
    "name": "Isobutavan",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=438702850",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Vanilla",
      "Apricot"
    ],
    "isAllergen": false,
    "ifraLimit": 2,
    "casNumber": "20665-85-4",
    "description": "Less powdery than vanillin and has a more creamy, thickening effect.",
    "longevity": 24,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "dimethyl_benzyl_carbinyl_butyrate",
    "name": "Dimethyl Benzyl Carbinyl Butyrate",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=524622161",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Apple",
      "Plum",
      "Rose",
      "Violet"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "10094-34-5",
    "description": "Apple, plum, rose and violet builder.",
    "longevity": 1,
    "impact": 224,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "ethylene_brassylate",
    "name": "Ethylene Brassylate",
    "imageUrl": "https://loremflickr.com/320/240/spice?lock=636998211",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Musk",
      "Powdery",
      "Spicy",
      "Vanilla",
      "Ambrette"
    ],
    "isAllergen": false,
    "ifraLimit": 12,
    "casNumber": "105-95-3",
    "description": "An exceptionally tenacious musk and a good fixative. It plays well with other musks and is best used in combination. Reinforces florals and sweetness.",
    "longevity": 280,
    "impact": 40,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "galaxolide",
    "name": "Galaxolide",
    "imageUrl": "https://loremflickr.com/320/240/cloud?lock=684351172",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Musk"
    ],
    "isAllergen": false,
    "ifraLimit": 50,
    "casNumber": "1222-05-5",
    "description": "Also called Musk G. A clean, powerful and versatile iso-chroman musk with great persistence and a superb fragrance quality approaching the tone of macrocyclic musks.",
    "longevity": 200,
    "impact": 60,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "violiff",
    "name": "Violiff",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=463145241",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Violet",
      "Green",
      "Banana",
      "Marigold"
    ],
    "isAllergen": false,
    "ifraLimit": 2,
    "casNumber": "87731-18-8",
    "description": "Violet, violet leaf, marigold and banana builder. Blends well with pineapple and ginger.",
    "longevity": 6,
    "impact": 120,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "iso_amyl_acetate",
    "name": "Iso Amyl Acetate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=302711269",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Banana",
      "Fruity"
    ],
    "isAllergen": false,
    "ifraLimit": 1,
    "casNumber": "123-92-2",
    "description": "Banana builder. Florals support. Very strong.",
    "longevity": 4,
    "impact": 800,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "melonal",
    "name": "Melonal",
    "imageUrl": "https://loremflickr.com/320/240/melon?lock=948353566",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Fresh",
      "Melon",
      "Green",
      "Cucumber",
      "Marine"
    ],
    "isAllergen": false,
    "ifraLimit": 0.2,
    "casNumber": "106-72-9",
    "description": "Powerful and invaluable in the creation of natural smelling marine and fruity-melon notes.",
    "longevity": 4,
    "impact": 700,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "lilial",
    "name": "Lilial",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=1102727835",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Lily",
      "Green",
      "Fresh",
      "Lilac"
    ],
    "isAllergen": false,
    "ifraLimit": 15,
    "casNumber": "80-54-6",
    "description": "Also called Lilestralis. Lilac and lily builder. Muguet builder.",
    "longevity": 72,
    "impact": 80,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "hedione",
    "name": "Hedione",
    "imageUrl": "https://loremflickr.com/320/240/citrus?lock=798236900",
    "vendor": "Firmenich",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Jasmine",
      "Citrus",
      "Floral",
      "Diffusive"
    ],
    "isAllergen": false,
    "ifraLimit": 50,
    "casNumber": "24851-98-7",
    "description": "An elegant, transparent jasmine note with a citrus freshness. Creates a natural smoothness and radiance in a wide range of perfume types.",
    "longevity": 160,
    "impact": 65,
    "flashPoint": 120,
    "vaporPressure": 0.001,
    "smiles": "COC(=O)CC1C(C2=CC=CCC2)C(=O)CCCC1=O",
    "olfactoryProfile": { "Floral": 80, "Citrus": 40, "Fresh": 60 },
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "veloutone",
    "name": "Veloutone",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=1754526261",
    "vendor": "Firmenich",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Jasmine",
      "Lactonic",
      "Fruity",
      "Peach",
      "Apricot"
    ],
    "isAllergen": false,
    "ifraLimit": 2,
    "casNumber": "65443-14-3",
    "description": "Has exceptional stability and makes a wonderful soft floral note in jasmine, tuberose, honeysuckle, muguet, lilac and fruity accords.",
    "longevity": 12,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "jasmatone",
    "name": "Jasmatone",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=1134699042",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral",
      "Fruity",
      "Peach",
      "Jasmine"
    ],
    "isAllergen": false,
    "ifraLimit": 4,
    "casNumber": "13074-65-2",
    "description": "Suitable for jasmine, floral and fruity fragrances.",
    "longevity": 72,
    "impact": 80,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "indolene_50",
    "name": "Indolene 50",
    "imageUrl": "https://loremflickr.com/320/240/texture?lock=41001434",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Indole",
      "Animalic",
      "Jasmine"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "68908-82-7",
    "description": "Jasmine builder, useful for extending longevity.",
    "longevity": 340,
    "impact": 150,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "benzyl_acetate",
    "name": "Benzyl Acetate",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=503424516",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Floral",
      "Jasmine",
      "Fresh",
      "Fruity",
      "Gardenia"
    ],
    "isAllergen": false,
    "ifraLimit": 25,
    "casNumber": "140-11-4",
    "description": "Almost essential in jasmine and gardenia accords.",
    "longevity": 15,
    "impact": 120,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "decalactone_delta",
    "name": "Decalactone Delta",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=405368954",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Lactonic",
      "Coconut"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "705-86-2",
    "description": "Milk note builder, coconut builder.",
    "longevity": 300,
    "impact": 150,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "octalactone_gamma",
    "name": "Octalactone Gamma",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1005796089",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Lactonic",
      "Coconut"
    ],
    "isAllergen": false,
    "ifraLimit": 1.6,
    "casNumber": "104-50-7",
    "description": "Milk note builder, coconut builder.",
    "longevity": 145,
    "impact": 500,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "dihydrocoumarin",
    "name": "Dihydrocoumarin",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1800549797",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Lactonic",
      "Coconut",
      "Vanilla",
      "Tonka",
      "Rose"
    ],
    "isAllergen": true,
    "ifraLimit": 0.43,
    "casNumber": "119-84-6",
    "description": "Milk note builder, coconut builder, vanilla builder.",
    "longevity": 38,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "clarycet",
    "name": "Clarycet",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=691693203",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Herbal",
      "Floral",
      "Rose",
      "Chamomile",
      "Plum",
      "Sage"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "131766-73-9",
    "description": "Augments rose ketone notes. Sage builder.",
    "longevity": 25,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "guaiacol",
    "name": "Guaiacol",
    "imageUrl": "https://loremflickr.com/320/240/spice?lock=1538427883",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Phenolic",
      "Spicy",
      "Smoke",
      "Vanilla",
      "Leather"
    ],
    "isAllergen": false,
    "ifraLimit": 0.5,
    "casNumber": "90-05-1",
    "description": "A powerful chemical. It can make a wood smokier, an incense deeper, and it brings out vanilla aspects in other materials when they have it. Deepens phenolic notes in leather accords.",
    "longevity": 132,
    "impact": 150,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "ambrettolide",
    "name": "Ambrettolide",
    "imageUrl": "https://loremflickr.com/320/240/cloud?lock=1699670364",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Ambrette",
      "Musk"
    ],
    "isAllergen": false,
    "ifraLimit": 2,
    "casNumber": "28645-51-4",
    "description": "Ambrettolide is a macrocyclic musk with an exceptional diffusion and a very fine character. A superb fixative and highly substantive. Used in trace amounts to great effect.",
    "longevity": 450,
    "impact": 30,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "edenolide",
    "name": "Edenolide",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=1278302427",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Musk",
      "Fruity",
      "Apple"
    ],
    "isAllergen": false,
    "ifraLimit": 30,
    "casNumber": "478695-70-4",
    "description": "A powdery, creamy, warm, relaxed sensuous white musk with fresh fruity nuances and soft comforting textures.",
    "longevity": 50,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "isoraldeine_95",
    "name": "Isoraldeine 95",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=1248211692",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Orris",
      "Violet",
      "Powdery",
      "Floral"
    ],
    "isAllergen": true,
    "ifraLimit": 30,
    "casNumber": "1335-46-2",
    "description": "Often used in flowery, woody, spicy and amber accords. It brings volume and diffusion to compounds. Also called Methyl Ionone Gamma 95.",
    "longevity": 180,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "allyl_cyclohexyl_propionate",
    "name": "Allyl Cyclohexyl Propionate",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=1707581315",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Fruity",
      "Green",
      "Waxy",
      "Apple",
      "Pineapple"
    ],
    "isAllergen": true,
    "ifraLimit": 30,
    "casNumber": "2705-87-5",
    "description": "Imparts texture and ripe fruity impressions. Very strong when undiluted.",
    "longevity": 200,
    "impact": 130,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "linalool",
    "name": "Linalool",
    "imageUrl": "https://loremflickr.com/320/240/citrus?lock=1185676944",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Citrus",
      "Orange",
      "Lemon",
      "Floral",
      "Waxy",
      "Aldehyde"
    ],
    "isAllergen": false,
    "ifraLimit": 12,
    "casNumber": "78-70-6",
    "description": "A good general builder. Appears in all kinds of compositions from floral to citrus.",
    "longevity": 10,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "ethyl_maltol",
    "name": "Ethyl Maltol",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=115249708",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Caramel",
      "Jammy"
    ],
    "isAllergen": false,
    "ifraLimit": 0.2,
    "casNumber": "4940-11-8",
    "description": "Gourmand builder. Creates realistic fruit accords with other ester-y materials.",
    "longevity": 200,
    "impact": 2500,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "hercolyn_d",
    "name": "Hercolyn D",
    "imageUrl": "https://loremflickr.com/320/240/amber?lock=934880901",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Fixative",
      "Amber"
    ],
    "isAllergen": false,
    "ifraLimit": 20,
    "casNumber": "8050-15-5",
    "description": "Very low odor strength. Amber builder. Has extremely useful fixative effects.",
    "longevity": 400,
    "impact": 25,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "vetacetex",
    "name": "Vetacetex",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=153252695",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Fresh",
      "Vetiver",
      "Wood"
    ],
    "isAllergen": false,
    "ifraLimit": 20,
    "casNumber": "68917-34-0",
    "description": "Vetiver builder.",
    "longevity": 300,
    "impact": 80,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "sylvamber",
    "name": "Sylvamber",
    "imageUrl": "https://loremflickr.com/320/240/amber?lock=734864269",
    "vendor": "DRT",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Amber",
      "Cedar",
      "Wood"
    ],
    "isAllergen": true,
    "ifraLimit": 20,
    "casNumber": "54464-57-2",
    "description": "Tenacious and diffusive, similar to Iso E Super.",
    "longevity": 400,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "cetalox",
    "name": "Cetalox",
    "imageUrl": "https://loremflickr.com/320/240/amber?lock=670220966",
    "vendor": "Firmenich",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Musk",
      "Ambergris",
      "Amber"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "3738-00-9",
    "description": "Enhanced richness, warmth and depth can be achieved at lower dosages while, at higher levels, Cetalox provides exceptional substantivity and performance.",
    "longevity": 400,
    "impact": 400,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "fructone",
    "name": "Fructone",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=1081162548",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Apple",
      "Strawberry",
      "Fruity",
      "Pineapple",
      "Tropical"
    ],
    "isAllergen": false,
    "ifraLimit": 30,
    "casNumber": "6413-10-1",
    "description": "Fructone is useful in fruity compositions and gives a fermented connotation at high dosages. Useful in some rose, aromatic, and green accords.",
    "longevity": 12,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "aprifloren",
    "name": "Aprifloren",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=380444088",
    "vendor": "Symrise",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Peach",
      "Green",
      "Lactonic",
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "67663-01-8",
    "description": "Adds richness and body to white floral compositions. Excellent diffusivity.",
    "longevity": 180,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "magnolan",
    "name": "Magnolan",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=64887099",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Grapefruit",
      "Peony",
      "Geranium",
      "Gardenia",
      "Rose"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "27606-09-3",
    "description": "White floral builder. Can be useful as a rose builder as well. Substantive and tenacious.",
    "longevity": 120,
    "impact": 80,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "anisyl_acetone",
    "name": "Anisyl Acetone",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1711680672",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Raspberry",
      "Cherry",
      "Heliotrope",
      "Rose",
      "Cassis"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "104-20-1",
    "description": "Raspberry, cherry, heliotrope and rose builder. Long lasting.",
    "longevity": 320,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "cyclabute",
    "name": "Cyclabute",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=1564562970",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Cocoa",
      "Pineapple",
      "Mango",
      "Herbal",
      "Balsamic",
      "Amber",
      "Fruity"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "67634-20-2",
    "description": "Fruity top note with amber and chocolate nuances.",
    "longevity": 340,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "bicyclononalactone",
    "name": "Bicyclononalactone",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1272721827",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Powdery",
      "Tonka",
      "Almond",
      "Vanilla",
      "Coconut",
      "Hay",
      "Coumarin"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "4430-31-3",
    "description": "A coumarin alternative that is more stable. It also has a very good tonka bean characteristic.",
    "longevity": 350,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "nectaryl",
    "name": "Nectaryl",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=823584620",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Peach",
      "Lactonic",
      "Fruity",
      "Apricot"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "95962-14-4",
    "description": "Peach and apricot builder. Supports milk accords.",
    "longevity": 380,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "methyl_benzoate",
    "name": "Methyl Benzoate",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1821972402",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Tuberose",
      "Cassis",
      "Wintergreen"
    ],
    "isAllergen": false,
    "ifraLimit": 2.3,
    "casNumber": "93-58-3",
    "description": "Used with ylang ylang, oakmoss, sandalwood, vetiver and musks.",
    "longevity": 10,
    "impact": 500,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "jessemal",
    "name": "Jessemal",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=1395432914",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Jasmine",
      "Floral",
      "Spicy"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "38285-49-3",
    "description": "A good jasmine note, extremely rich and stable.",
    "longevity": 350,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "anisyl_alcohol",
    "name": "Anisyl Alcohol",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1967340345",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Hawthorn",
      "Lilac",
      "Jasmine",
      "Mimosa",
      "Heliotrope",
      "Powdery",
      "Vanilla",
      "Balsamic"
    ],
    "isAllergen": true,
    "ifraLimit": 0.21,
    "casNumber": "105-13-5",
    "description": "Very useful in lilac, apple blossom, pea, gardenia, jasmine and heliotrope accords.",
    "longevity": 30,
    "impact": 80,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "sandalore",
    "name": "Sandalore",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1647026387",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Sandalwood"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "65113-99-7",
    "description": "Powerful, diffusive and tenacious sandalwood builder. Works well with Ebanol.",
    "longevity": 330,
    "impact": 75,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "sandela",
    "name": "Sandela",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1865402774",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Sandalwood"
    ],
    "isAllergen": false,
    "ifraLimit": 20,
    "casNumber": "70955-71-4",
    "description": "A tenacious sandalwood builder.",
    "longevity": 400,
    "impact": 20,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "decalactone_gamma",
    "name": "Decalactone Gamma",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=408021097",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Coconut",
      "Apricot",
      "Peach",
      "Lactonic"
    ],
    "isAllergen": false,
    "ifraLimit": 12,
    "casNumber": "706-14-9",
    "description": "Milk note builder, coconut builder. White floral support.",
    "longevity": 50,
    "impact": 180,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "methyl_cyclo_pentenolone",
    "name": "Methyl Cyclo Pentenolone",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=493524330",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Caramel",
      "Coffee",
      "Nutty"
    ],
    "isAllergen": false,
    "ifraLimit": 3,
    "casNumber": "765-70-8",
    "description": "Also called maple lactone. Coffee builder. Caramel builder. Gourmand builder. Powerful when undiluted.",
    "longevity": 16,
    "impact": 150,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "iso_e_super",
    "name": "Iso E Super",
    "imageUrl": "https://images.unsplash.com/photo-1542614471-001ccf2b449c?auto=format&fit=crop&q=80&w=200", // Placeholder for Woody/Amber
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Amber",
      "Citrus",
      "Ambergris",
      "Diffusive"
    ],
    "isAllergen": false,
    "ifraLimit": 20,
    "casNumber": "54464-57-2",
    "description": "Extremely diffusive. Used to impart fullness and subtle strength to fragrances, especially floral compositions.",
    "longevity": 48,
    "impact": 280,
    "flashPoint": 104,
    "vaporPressure": 0.002,
    "smiles": "CC1(C)C2CC=C(C)C(C2)C1C(=O)C",
    "olfactoryProfile": { "Woody": 90, "Amber": 70, "Floral": 10 },
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "ebanol",
    "name": "Ebanol",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=1309919001",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Sandalwood"
    ],
    "isAllergen": true,
    "ifraLimit": 10,
    "casNumber": "67801-20-1",
    "description": "Powerful and intense, bringing volume and elegance to woody accords and a diffusive sandalwood effect to compositions.",
    "longevity": 500,
    "impact": 125,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "kephalis",
    "name": "Kephalis",
    "imageUrl": "https://loremflickr.com/320/240/amber?lock=251211367",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Amber",
      "Tobacco",
      "Herbal"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "36306-87-3",
    "description": "Blends well with floral notes as well as ISO E Super, amber notes, wood, and tobacco.",
    "longevity": 100,
    "impact": 80,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "dihydro_ionone_beta",
    "name": "Dihydro Ionone Beta",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=2012002173",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Orris",
      "Amber",
      "Fruity"
    ],
    "isAllergen": false,
    "ifraLimit": 3.5999999999999996,
    "casNumber": "17283-81-7",
    "description": "Brings a rich sophisticated volume to perfumes in combination with floral and amber elements.",
    "longevity": 80,
    "impact": 220,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "raspberry_ketone",
    "name": "Raspberry Ketone",
    "imageUrl": "https://loremflickr.com/320/240/berry?lock=1169197537",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Fruity",
      "Raspberry",
      "Jammy"
    ],
    "isAllergen": true,
    "ifraLimit": 1,
    "casNumber": "5471-51-2",
    "description": "Powerful and very deep and jammy, this material can be easily pushed in the direction of other fruits when used in combination with other materials. Can add fruity nuance to floral compositions.",
    "longevity": 350,
    "impact": 70,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "auralva",
    "name": "Auralva",
    "imageUrl": "https://loremflickr.com/320/240/citrus?lock=648566828",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Neroli",
      "Tuberose",
      "Citrus",
      "Orange",
      "Grape"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "89-43-0",
    "description": "Neroli and tuberose builder. Useful in citrus, amber, chypre and oriental compositions as well. Blends well with macrocyclic musks.",
    "longevity": 400,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "orange_flower_ether",
    "name": "Orange Flower Ether",
    "imageUrl": "https://loremflickr.com/320/240/orange?lock=462209133",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Neroli",
      "Citrus"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "14576-08-0",
    "description": "Neroli builder. Useful in citrus compositions as well.",
    "longevity": 3,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "stemone",
    "name": "Stemone",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=1893644547",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Green",
      "Fig"
    ],
    "isAllergen": false,
    "ifraLimit": 0.8,
    "casNumber": "22457-23-4",
    "description": "Imparts a natural and fresh nuance to fragrance notes such as lily-of-the-valley, narcissus, mandarin, fig leaves, fig, grapefruit, black currant and tomato. Very strong.",
    "longevity": 8,
    "impact": 1000,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "cyclamen_aldehyde",
    "name": "Cyclamen Aldehyde",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=1738731671",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral",
      "Fresh",
      "Green",
      "Cucumber",
      "Melon",
      "Rhubarb"
    ],
    "isAllergen": true,
    "ifraLimit": 0.95,
    "casNumber": "103-95-7",
    "description": "Powerful and versatile green note. Extensively used in perfumery for floral effects and fresh green floral top notes.",
    "longevity": 40,
    "impact": 75,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "phenyl_ethyl_alcohol",
    "name": "Phenyl Ethyl Alcohol",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=556882256",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Rose",
      "Green",
      "Honey",
      "Melon"
    ],
    "isAllergen": false,
    "ifraLimit": 33,
    "casNumber": "60-12-8",
    "description": "Rose and muguet builder. Good general all-around floral builder. ",
    "longevity": 24,
    "impact": 60,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "fructalate",
    "name": "Fructalate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=371887981",
    "vendor": "Firmenich",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Fruity",
      "Raspberry",
      "Apple"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "72903-27-6",
    "description": "In small doses you can use it to enhance diffusion of almost any fragrance. Larger proportions will create a fruitiness that is dry rather than sweet and can be pushed in the direction of almost any fruit.",
    "longevity": 48,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "exaltolide_total",
    "name": "Exaltolide Total",
    "imageUrl": "https://loremflickr.com/320/240/cloud?lock=1474974300",
    "vendor": "Firmenich",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Musk",
      "Powdery",
      "Animalic"
    ],
    "isAllergen": true,
    "ifraLimit": 2.4,
    "casNumber": "106-02-5",
    "description": "Adds depth and roundness to a wide variety of creations but it also has a synergistic effect on the bouquet of a fragrance.",
    "longevity": 400,
    "impact": 150,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "bacdanol",
    "name": "Bacdanol",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=2114869162",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Sandalwood"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "28219-61-6",
    "description": "Powerful and diffusive sandalwood builder.",
    "longevity": 300,
    "impact": 80,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "nectarate",
    "name": "Nectarate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=238703271",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Peach",
      "Fruity"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "113889-23-9",
    "description": "Pleasant, fruity, peach note with a slight woody undertone. Useful in a wide variety of fragrances, giving a substantive fruity note even through washing cycles.",
    "longevity": 140,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "fraistone",
    "name": "Fraistone",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=444496625",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Anise",
      "Fruity",
      "Apple",
      "Plum",
      "Strawberry"
    ],
    "isAllergen": false,
    "ifraLimit": 30,
    "casNumber": "6290-17-1",
    "description": "Strawberry, apple and plum builder.",
    "longevity": 12,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "citronellyl_acetate",
    "name": "Citronellyl Acetate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=1622406025",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Rose",
      "Fruity",
      "Geranium"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "150-84-5",
    "description": "Rose and geranium builder.",
    "longevity": 15,
    "impact": 110,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "cashmeran",
    "name": "Cashmeran",
    "imageUrl": "https://loremflickr.com/320/240/spice?lock=769470516",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Apple",
      "Spicy",
      "Powdery",
      "Musk",
      "Velvet"
    ],
    "isAllergen": false,
    "ifraLimit": 2,
    "casNumber": "33704-61-9",
    "description": "Very diffusive and strong floral reinforcement. Combines especially well with Allyl Amyl Glycolate, Delta Damascone, tea accords, myrrh, and green notes. Useful in creating spicy florals, amber notes, musk notes and wood accords.",
    "longevity": 200,
    "impact": 80,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "acetophenone",
    "name": "Acetophenone",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=179040729",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Cherry",
      "Powdery",
      "Hawthorn",
      "Mimosa",
      "Neroli"
    ],
    "isAllergen": false,
    "ifraLimit": 2,
    "casNumber": "98-86-2",
    "description": "Almond, mimosa, hawthorn, neroli, and cherry builder. Also called phenyl methyl ketone.",
    "longevity": 8,
    "impact": 200,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "benzyl_propionate",
    "name": "Benzyl Propionate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=717177450",
    "vendor": "Symrise",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Jasmine",
      "Grape",
      "Pear",
      "Banana",
      "Fruity",
      "Pineapple"
    ],
    "isAllergen": false,
    "ifraLimit": 6.7,
    "casNumber": "122-63-4",
    "description": "Fruit builder, jasmine builder.",
    "longevity": 20,
    "impact": 120,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "benzyl_salicylate",
    "name": "Benzyl Salicylate",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=2070937572",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Floral",
      "Jasmine"
    ],
    "isAllergen": false,
    "ifraLimit": 32,
    "casNumber": "118-58-1",
    "description": "Good fixative for jasmine, ylang-ylang, frangipani and other floral accords.",
    "longevity": 210,
    "impact": 30,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "ambroxan",
    "name": "Ambroxan",
    "imageUrl": "https://images.unsplash.com/photo-1618331835717-801e976710b2?auto=format&fit=crop&q=80&w=200", // Placeholder for Ambergris
    "vendor": "Kao",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Masculine",
      "Fresh",
      "Musk"
    ],
    "isAllergen": false,
    "ifraLimit": 2,
    "casNumber": "3738-00-9",
    "description": "Used to amplify heart notes. Has useful fixative properties.",
    "longevity": 740,
    "impact": 400,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "allyl_amyl_glycoate",
    "name": "Allyl Amyl Glycoate",
    "imageUrl": "https://loremflickr.com/320/240/leaf?lock=1177705063",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Fruity",
      "Green",
      "Herbal",
      "Pineapple",
      "Fresh",
      "Galbanum"
    ],
    "isAllergen": false,
    "ifraLimit": 4,
    "casNumber": "67634-00-8",
    "description": "Pineapple builder. Adds a modern sparkle to fragrances.",
    "longevity": 10,
    "impact": 170,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "amyl_cinnamic_aldehyde",
    "name": "Amyl Cinnamic Aldehyde",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=2065824817",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Base",
    "olfactiveFamilies": [
      "Floral",
      "White floral",
      "Jasmine"
    ],
    "isAllergen": false,
    "ifraLimit": 30,
    "casNumber": "122-40-7",
    "description": "White floral builder. Tenacious.",
    "longevity": 250,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "amyl_salicylate",
    "name": "Amyl Salicylate",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=1821059033",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Floral",
      "Green",
      "Herbal",
      "Balsamic"
    ],
    "isAllergen": false,
    "ifraLimit": 8,
    "casNumber": "2050-08-0",
    "description": "Floral builder.",
    "longevity": 36,
    "impact": 110,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "apo_patchone_coeur",
    "name": "Apo Patchone Coeur",
    "imageUrl": "https://loremflickr.com/320/240/flower?lock=558013580",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Diffusive",
      "Leather",
      "Feminine",
      "Floral"
    ],
    "isAllergen": false,
    "ifraLimit": 10,
    "casNumber": "4621-04-9",
    "description": "Leather builder with a feminine touch. Also called leather cyclohexanol.",
    "longevity": 12,
    "impact": 100,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "diethyl_malonate",
    "name": "Diethyl Malonate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=1053494733",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Apple",
      "Fruity"
    ],
    "isAllergen": false,
    "ifraLimit": 6.2,
    "casNumber": "105-53-3",
    "description": "Powerful and versatile green note. Extensively used in perfumery for floral effects and fresh green floral top notes.",
    "longevity": 2,
    "impact": 80,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "ethyl_acetate",
    "name": "Ethyl Acetate",
    "imageUrl": "https://loremflickr.com/320/240/fruit?lock=1563411918",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Fruity",
      "Brandy",
      "Grape"
    ],
    "isAllergen": false,
    "ifraLimit": 18,
    "casNumber": "141-78-6",
    "description": "Used to make top notes more alcoholic or to give lift to top notes.",
    "longevity": 4,
    "impact": 120,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "grape_butyrate",
    "name": "Grape Butyrate",
    "imageUrl": "https://loremflickr.com/320/240/grape?lock=1234077548",
    "vendor": "Generic",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Grape",
      "Diffusive",
      "Fruity"
    ],
    "isAllergen": false,
    "ifraLimit": 2.1999999999999997,
    "casNumber": "5405-41-4",
    "description": "Very diffusive grape scent. Also called ethyl 3-hydroxybutyrate.",
    "longevity": 4,
    "impact": 100,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "ionone_beta",
    "name": "Ionone Beta",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=710885425",
    "vendor": "IFF",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Orris",
      "Violet",
      "Raspberry"
    ],
    "isAllergen": false,
    "ifraLimit": 6.7,
    "casNumber": "79-77-6",
    "description": "Orris and violet builder.",
    "longevity": 100,
    "impact": 120,
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "lavender_aldehyde_fcc",
    "name": "Lavender Aldehyde FCC",
    "imageUrl": "https://loremflickr.com/320/240/lavender?lock=1258629181",
    "vendor": "Bedoukian",
    "cost": 0.5,
    "note": "Mid",
    "olfactiveFamilies": [
      "Lavender",
      "Sage",
      "Diffusive",
      "Herbal"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "35158-25-9",
    "description": "Sage and lavender builder. Diffusive.",
    "longevity": 8,
    "impact": 150,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "lime_oxide",
    "name": "Lime Oxide",
    "imageUrl": "https://loremflickr.com/320/240/lime?lock=1590463689",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Fresh",
      "Citrus",
      "Green",
      "Lime"
    ],
    "isAllergen": false,
    "ifraLimit": 5,
    "casNumber": "73018-51-6",
    "description": "Lime oxide adds freshness and intensity to perfumes.",
    "longevity": 4,
    "impact": 300,
    "concentration": 10,
    "dilution": 10
  },
  {
    "id": "methylbutyraldehyde",
    "name": "Methylbutyraldehyde",
    "imageUrl": "https://loremflickr.com/320/240/perfume?lock=916245721",
    "vendor": "Givaudan",
    "cost": 0.5,
    "note": "Top",
    "olfactiveFamilies": [
      "Cocoa",
      "Chocolate",
      "Coffee"
    ],
    "isAllergen": false,
    "ifraLimit": 2,
    "casNumber": "96-17-3",
    "description": "Cocoa builder. Chocolate builder. Coffee builder. Very strong.",
    "longevity": 2,
    "impact": 300,
    "concentration": 1,
    "dilution": 1
  },
  {
    "id": "bergamot_reggio",
    "name": "Bergamot Reggio",
    "imageUrl": "https://loremflickr.com/320/240/bergamot?lock=78323439",
    "vendor": "Capua",
    "cost": 1.2,
    "note": "Top",
    "olfactiveFamilies": ["Citrus", "Green", "Fresh"],
    "isAllergen": true,
    "ifraLimit": 0.4,
    "casNumber": "8007-75-8",
    "description": "The finest bergamot oil from Reggio Calabria. Complex, fresh, sparkling, and floral.",
    "longevity": 6,
    "impact": 100,
    "flashPoint": 58,
    "vaporPressure": 0.5,
    "smiles": "CC1=CCC(CC1)C(C)(C)O",
    "olfactoryProfile": { "Citrus": 90, "Floral": 30, "Green": 40 },
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "rose_abs_bulgarian",
    "name": "Bulgarian Rose Abs.",
    "imageUrl": "https://images.unsplash.com/photo-1496857239036-1fb13768f0db?auto=format&fit=crop&q=80&w=200", // Placeholder for Rose
    "vendor": "Generic",
    "cost": 12.5,
    "note": "Mid",
    "olfactiveFamilies": ["Floral", "Spicy", "Honey"],
    "isAllergen": true,
    "ifraLimit": 0.02,
    "casNumber": "90106-38-0",
    "description": "Rosa damascena via solvent extraction. Rich, spicy, floral profile with honey undertones.",
    "longevity": 24,
    "impact": 300,
    "flashPoint": 68,
    "vaporPressure": 0.02,
    "smiles": "CC(C)=CCCC(C)=CCO",
    "olfactoryProfile": { "Floral": 95, "Spicy": 60, "Green": 40, "Honey": 35 },
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "oud_wood",
    "name": "Oud Wood (Agar)",
    "imageUrl": "https://loremflickr.com/320/240/oud?lock=403527922",
    "vendor": "Generic",
    "cost": 50,
    "note": "Base",
    "olfactiveFamilies": ["Woody", "Animalic", "Balsamic"],
    "isAllergen": false,
    "ifraLimit": 100,
    "casNumber": "94350-09-1",
    "description": "Precious agarwood oil. Deep, woody, animalic, and balsamic nuances.",
    "longevity": 168,
    "impact": 500,
    "flashPoint": 120,
    "vaporPressure": 0.001,
    "smiles": "CC12CCC(CC1(C)CCCC2(C)O)C(C)C",
    "olfactoryProfile": { "Woody": 90, "Animalic": 70, "Balsamic": 50 },
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "lemon_oil",
    "name": "Lemon Oil",
    "imageUrl": "https://loremflickr.com/320/240/lemon?lock=765352314",
    "vendor": "Generic",
    "cost": 0.8,
    "note": "Top",
    "olfactiveFamilies": ["Citrus", "Fresh", "Zesty"],
    "isAllergen": true,
    "ifraLimit": 2,
    "casNumber": "8008-56-8",
    "description": "Cold pressed lemon oil. Sharp, fresh, and zesty.",
    "longevity": 4,
    "impact": 120,
    "flashPoint": 48,
    "vaporPressure": 0.8,
    "smiles": "CC1=CCC(CC1)C(=C)C",
    "olfactoryProfile": { "Citrus": 95, "Zesty": 80, "Green": 20 },
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "labdanum_abs",
    "name": "Labdanum Abs",
    "imageUrl": "https://loremflickr.com/320/240/resin?lock=41596369",
    "vendor": "Generic",
    "cost": 4.5,
    "note": "Base",
    "olfactiveFamilies": ["Amber", "Balsamic", "Leather"],
    "isAllergen": false,
    "ifraLimit": 100,
    "casNumber": "8016-26-0",
    "description": "Rich, balsamic, sweet, and leathery. Essential for amber accords.",
    "longevity": 100,
    "impact": 200,
    "flashPoint": 100,
    "vaporPressure": 0.01,
    "smiles": "CC1(C)CCCC(C)(O)C1",
    "olfactoryProfile": { "Amber": 90, "Leather": 50, "Balsamic": 80 },
    "concentration": 100,
    "dilution": 100
  },
  {
    "id": "benzoin_siam",
    "name": "Benzoin Siam",
    "imageUrl": "https://loremflickr.com/320/240/resin?lock=828521764",
    "vendor": "Generic",
    "cost": 2.5,
    "note": "Base",
    "olfactiveFamilies": ["Balsamic", "Sweet", "Vanilla"],
    "isAllergen": false,
    "ifraLimit": 2,
    "casNumber": "9000-05-9",
    "description": "Sweet, balsamic, and vanilla-like resinoid.",
    "longevity": 80,
    "impact": 150,
    "flashPoint": 100,
    "vaporPressure": 0.01,
    "smiles": "O=C(O)C1=CC=CC=C1",
    "olfactoryProfile": { "Sweet": 85, "Balsamic": 70, "Vanilla": 60 },
    "concentration": 100,
    "dilution": 100
  }
];
